### ISSUE TITLE
vignette formatting

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#11]
Some of the vignettes are not properly formatted when installed. Most notably, section headers do not render due to a lack of space between `#`, `##`, or `###` and the header. Some, for example `test_graph_network_inhibiting`, include very little text and therefore function more as examples than as vignettes. Would it make sense to trim and/or combine the existing vignettes into a smaller number that are more comprehensive and contain thorough exposition?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
As discussed [here](https://github.com/TomKellyGenetics/graphsim/issues/6#issuecomment-607684815), I had some issues submitting to CRAN due to file size limitations. I agree that vignettes are important to guide users so I will review this and see if it possible to expand them within the limitations of CRAN. Examples in documentation (help menu) will be [updated](https://github.com/TomKellyGenetics/graphsim/issues/6) to match the vignettes.

**Comment by corybrunson** [comment]
That sounds good—though it's quite OK for the vignettes to complement the help examples; there's no need to have them consist of the same code, in case that's what you meant. I look forward to exploring the updated vignettes. Thanks.

**Comment by TomKellyGenetics** [comment]
Vignettes have substantially revised. It's still a work in progress in terms of figures formatting but the code examples are working as expected. I'll update the documentation to address #6  and #13 using similar examples to this.

**Comment by TomKellyGenetics** [comment]
Here is a preview of the rendered [vignettes](https://github.com/TomKellyGenetics/graphsim/files/4856451/vignettes.zip), I'll try get this through CRAN checks/build soon.

**Comment by corybrunson** [comment]
The previews look good! The only suggestions i have are

* to consider arranging the figures in grids, or at least putting some pairs on the same line, so that more figures can be viewed on the screen at once; and
* to wrap the recurring analysis steps in a single function (not a package function, just a function defined at the beginning of the vignette) that can be called to produce each set of figures without a large code chunk.

But those are, again, suggestions. I'll keep the issue open until they're installable.

**Comment by TomKellyGenetics** [comment]
Related issue #14: the vignettes are too large for CRANs regular checks so a revised version will need to be pushed in coming weeks.

**Comment by TomKellyGenetics** [comment]
Thanks for the suggestions. I think these are good ideas but they're taking longer to get back to than I expected. Putting figures into columns (as I did in the manuscript) seems to be tricky in the vignette Rmd style. I need more time to see if this is possible.

The corrections to build time on CRAN are more pressing. The automated checks time-out which can be problematic. I need to submit a quick release (which will address #6 and #14) to avoid the package being "archived" by our benevolent CRAN overlords. I will do this before I go on holiday next week and come back to this issue and whether it can be done in a future release later on.

**Comment by corybrunson** [comment]
That makes eminent sense! I do hope the formatting issues can be resolved, but i agree that the more pressing matter is to get, and keep, the package functional and conveniently accessible. Thanks for the updates—i'll continue to pay attention and chime in as seems appropriate. : )

**Comment by TomKellyGenetics** [comment]
To  clarify, the package works but one of the examples in the vignette takes too long to run for the regular checks on CRAN. I'd hoped to bundle everything into the next release but I've been in zoom conferences this week so I'm short on time. Thanks for understanding!

**Comment by TomKellyGenetics** [comment]
I seem to have broken knitr vignette builder so the current release (1.0.1) uses pre-generated HTMLs from `R.rsp::asis`. I'm not entirely satisfied with this so I will revisit the vignettes when I have more time. This seems to satisfy the CRAN checks in the meantime.

**Comment by TomKellyGenetics** [comment]
@corybrunson sorry it has been far too long to address this, it is still on my list. I've encountered a bug in the plotting function so a new release for CRAN is on the way. I've been using the plotting function for another package. In addition to updating the other package, I've also been preparing a new "graphsim" vignette for this release (as suggested by my PhD supervisor). Ideally, release the new vignette at the same time which may delay this.

**Comment by corybrunson** [comment]
@TomKellyGenetics no problem, i'm still watching and will be glad to take a look whenever an update is ready!

**Comment by TomKellyGenetics** [comment]
Haven't had time to update the vignettes yet. I suspect this issue itself isn't much trouble but I'd like to bundle it with more documentation in the next release. 

Just to note that CRAN checks now identify some other issues. This seems to be due to updates in the checks themselves. It seems to be okay on CRAN for now but these will need to addressed in the next version too. 
https://cran.r-project.org/web/checks/check_results_graphsim.html

**Comment by TomKellyGenetics** [comment]
This issue is resolved in the [v1.0.2](https://github.com/TomKellyGenetics/graphsim/releases/tag/v1.0.2) release. Main purpose of this _minor_ release is to update my contact details before changing jobs.

The additional vignette to import graph structures directly into R is still in progress. I've recently returned from parental leave and not had time to work on it further. One of the main issues is that it depends on old versions of BioPAX, PathwayCommons, and Bioconductor packages.
