### ISSUE TITLE
edges not rendered using character argument to state parameter

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#3]
I'm just running through the examples in the JOSS paper, and i've encountered a problem with the `plot_directed()` function. As illustrated below, while the function accepts the correctly-spelled character string (contrast to when the string is misspelled), it fails to render the edges; they are successfully rendered when using a numeric sign (`1` or `-1`) instead of a character.

I have igraph installed from CRAN, and i installed the current version of graphsim from GitHub.

``` r
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
library(graphsim)
graph_edges <- rbind(c("A", "C"), c("B", "C"), c("C", "D"), c("D", "E"),
                     c("D", "F"), c("F", "G"), c("F", "I"), c("H", "I"))
graph <- graph.edgelist(graph_edges, directed = TRUE)
# using the character string
plot_directed(graph, state = "activating", layout = layout.kamada.kawai,
              cex.node = 3, cex.arrow = 5, arrow_clip = 0.2)
```

![](https://i.imgur.com/36k01Ft.png)

``` r
# using a single sign
plot_directed(graph, state = 1, layout = layout.kamada.kawai,
              cex.node = 3, cex.arrow = 5, arrow_clip = 0.2)
```

![](https://i.imgur.com/vvvhseX.png)

``` r
# using a different character string
plot_directed(graph, state = "activate", layout = layout.kamada.kawai,
              cex.node = 3, cex.arrow = 5, arrow_clip = 0.2)
#> Warning in plot_directed(graph, state = "activate", layout =
#> layout.kamada.kawai, : please give state as a scalar or vector of
#> length(E(graph))
#> Error in plot_directed(graph, state = "activate", layout = layout.kamada.kawai, :
```

![](https://i.imgur.com/j95A32F.png)

<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
I've managed to identify the problem. The state parameter is applied to all edges when give as a scalar (`length(state) == 1`). The issue was that default colours (`col.arrow`) were not defined in the case of text inputs (so they were rendered as white).

This should be fixed in the development version (activating edges default to `par("fg")` and inhibiting edges default to `"red"`). See commit: 3236c0d399796e09ee3583214ddc6753ec870285

```
devtools::install_github("TomKellyGenetics/graphsim", ref = "dev")
```

Working example with test input:

``` r
library("graphsim")
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
graph_edges <- rbind(c("A", "C"), c("B", "C"), c("C", "D"), c("D", "E"),
                     c("D", "F"), c("F", "G"), c("F", "I"), c("H", "I"))
graph <- graph.edgelist(graph_edges, directed = TRUE)
# using the character string
plot_directed(graph, state = "activating", layout = layout.kamada.kawai,
              cex.node = 3, cex.arrow = 5, arrow_clip = 0.2)
```

![](https://i.imgur.com/S1BnSd8.png)

<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
library("graphsim")
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
graph_edges <- rbind(c("A", "C"), c("B", "C"), c("C", "D"), c("D", "E"),
                     c("D", "F"), c("F", "G"), c("F", "I"), c("H", "I"))
graph <- graph.edgelist(graph_edges, directed = TRUE)
# using the character string
plot_directed(graph, state = "inhibiting", layout = layout.kamada.kawai,
              cex.node = 3, cex.arrow = 5, arrow_clip = 0.2)
```

![](https://i.imgur.com/CuKFkKV.png)

<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Error handling when incorrect string given.

``` r
library("graphsim")
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
graph_edges <- rbind(c("A", "C"), c("B", "C"), c("C", "D"), c("D", "E"),
                     c("D", "F"), c("F", "G"), c("F", "I"), c("H", "I"))
graph <- graph.edgelist(graph_edges, directed = TRUE)
# using the character string
plot_directed(graph, state = "activate", layout = layout.kamada.kawai,
              cex.node = 3, cex.arrow = 5, arrow_clip = 0.2)
#> Warning in plot_directed(graph, state = "activate", layout =
#> layout.kamada.kawai, : please give state as a scalar or vector of
#> length(E(graph)): input must be 'activating', 'inhibiting' or an integer
#> Error in plot_directed(graph, state = "activate", layout = layout.kamada.kawai, :
```
I'll consider adding common aliases (e.g., "activate", "activation").

Vector input is also supported either directly calling the function with a value for each edge in `E(graph)` or as an edge "attribute" in the igraph object (using `E(g)$state <- states` as described [here](https://stackoverflow.com/questions/33813835/assigning-edge-weight-to-an-igraph-object-in-r)). Since this seems to be unclear, I'll review the documentations and consider adding more examples to demonstrate this.

<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by corybrunson** [comment]
Great—i'll update to the development version, and it would be good to have these changes merged into `master` in order to finish the review.

By the way, i did not mean to suggest that aliases _should_ be allowed! I only meant to illustrate what happens when an unrecognized character string is passed, which was different than what happens when a recognized string was passed. I leave it to you to decide how flexible the interface should be. Thank you!

**Comment by TomKellyGenetics** [comment]
Documentation has been updated for `plot_directed` and `make_state_matrix` (which both take a `state` parameter). The warning messages and aliases should make this more user-friendly.

I've merged this to master branch.
