### ISSUE TITLE
additional documentation

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#6]
Functions like `generate_expression()` and `plot_directed()` are documented with toy examples, while the four empirical networks included with the package are very sparsely documented. I think the value of the documentation in each case would be much increased by including illustrations that apply these functions to the empirical networks. Would this make sense to do, and would it be feasible? (Examples with long runtimes are discouraged by CRAN.)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
I think this is a good idea if CRAN will allow it. The TGF-Beta/Smad pathway was selected for the manuscript because should be a manageable to size to run examples (although the runtime will be longer than the test examples).

Would a vignette using the biological networks be helpful? I have tried pre-generating figures for vignettes in HTML but CRAN has a limit on package size of 5MB which makes this difficult. 

I'll review the examples in the documentation and see if it can pass CRAN checks.

**Comment by corybrunson** [comment]
It would make a lot of sense to use these examples in a vignette, especially if there's no room to use them in the examples.

By the way, the existing vignettes rely on the animation package (among others), though the package itself does not; so it would be helpful to mention, with the installation instructions, that these packages must be installed in order to build the vignettes when installing graphsim:

```r
remotes::install_github("TomKellyGenetics/graphsim", build_vignettes = TRUE)
```

**Comment by TomKellyGenetics** [comment]
Thanks I'll come back to the examples once the vignettes are update as per #11 and #13.

> By the way, the existing vignettes rely on the animation package (among others), though the package itself does not; so it would be helpful to mention, with the installation instructions, that these packages must be installed in order to build the vignettes when installing graphsim

I'll bear this in mind. I may consider removing additional dependencies for the vignettes that aren't strictly needed. I think `gplots` for "heatmap.2" may fall into this category (looking into it this should really be under `Suggests:` in this case).

**Comment by TomKellyGenetics** [comment]
Dependency on the `animation` package has been removed. Examples with empirical data are given in the vignettes. I'll relevant examples like this to the documentation `#' @usage` section if CRAN allows larger computations.

**Comment by corybrunson** [comment]
The documentation is much improved in the current version! Again i have a couple of suggestions, but these need not be met for me to recommend acceptance of the paper.

* While several objects (including functions) include links to related objects in their descriptions, others (for example, the `make_distance_*()` functions) don't include links to other documentation. Two roxygen2 fields that help cross-reference related objects are `@seealso` and `@family`.
* The package itself does not have a documentation page that can be accessed by `help(`graphsim-package`)` or just `help(graphsim)`. This isn't strictly necessary, but i find it very helpful. For an example, see [the package documentation for igraph](https://github.com/igraph/rigraph/blob/dev/R/igraph-package.R)—which is unusually long (in my experience) but showcases the kinds of elements that often make up such a page.

**Comment by TomKellyGenetics** [comment]
Thanks, I had some trouble with links recently actually (see 5bf900f6). There has been some updates to CRAN checks (as discussed here: https://github.com/r-lib/roxygen2/issues/707). Co-incidentally, this was caused by linking to the `help(igraph-package)` because you now have to link to the file name: [aaa-igraph-package](https://github.com/igraph/rigraph/blob/a14fc50abf9bf3ae17b870ccbc21f88d0eefed6e/R/igraph-package.R#L41).

I hadn't considered doing a "help" page for the overall package but I agree this may be helpful to describe the different functions. I'm planning to release a minor update to CRAN soon anyway so I look into including these suggestions (#6) or (#11) for that. This would also update citation information if the paper is accepted.

**Comment by TomKellyGenetics** [comment]
This is a work-in-progress (on `dev` branch). I'll try to have a `help(graphsim-package)` page ready for the next release but I may not have time to go into details, yet. I'm in conferences most of this week and taking the following week off (#14 needs to be addressed by then).

**Comment by TomKellyGenetics** [comment]
These are good suggestions though, thanks @corybrunson. Since it is not clear how the functions relate to each other I think the `help(graphsim-package)` (and vignettes) are helpful for users.

**Comment by TomKellyGenetics** [comment]
I think this is addressed by [graphsim-package.R](https://github.com/TomKellyGenetics/graphsim/blob/dev/R/graphsim-package.R) for a `help(graphsim-package)` call. I will try to get the vignettes compatible with CRAN checks and bundle this into a minor release in a few days.

**Comment by TomKellyGenetics** [comment]
Version 1.0.1 has been pushed to CRAN so I think we can close this one.

**Comment by corybrunson** [comment]
Fine by me! Kudos.
